cerebro/Models/AuditoriaView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cerebro.Models
{
    public class AuditoriaView
    {
        public IEnumerable<Models.TbAuditoria> Auditorias { get; set; }
        public DateTime? FeDesde { get; set; }
        public DateTime? FeHasta { get; set; }

        public string StrFeDesde { get; set; }

        public string StrFeHasta { get; set; }
    }
}

cerebro/Controllers/AuditoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using cerebro.Models;
using System.Globalization;

namespace cerebro.Controllers
{
    public class AuditoriaController : Controller
    {
        private readonly dbCerebroContext _context;
        private static readonly log4net.ILog logger = log4net.LogManager.GetLogger(typeof(AuditoriaController));

        public AuditoriaController(dbCerebroContext context)
        {
            _context = context;
        }

        // GET: Auditoria
        public IActionResult Index()
        {
            AuditoriaView AuditoriaViewPage = new AuditoriaView();
            //AuditoriaViewPage.FeDesde = DateTime.Now;
            //AuditoriaViewPage.FeHasta = DateTime.Now;
            AuditoriaViewPage.Auditorias = Enumerable.Empty<TbAuditoria>();
            return View(AuditoriaViewPage);

            /*
            var dbCerebroContext = _context.TbAuditoria;
            return View(await dbCerebroContext.ToListAsync());*/
        }

        [HttpPost]
        public IActionResult Index(AuditoriaView auditoriaView)
        {
            var errors = ModelState
               .Where(x => x.Value.Errors.Count > 0)
               .Select(x => new { x.Key, x.Value.Errors })
               .ToArray();
            logger.Debug("errors " + errors.ToString());

            if (!ModelState.IsValid)
            {
                var message = string.Join(" | ", ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));
                logger.Debug("message " + message);

            }

            auditoriaView.FeDesde = DateTime.ParseExact(auditoriaView.StrFeDesde, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            auditoriaView.FeHasta = DateTime.ParseExact(auditoriaView.StrFeHasta, "dd/MM/yyyy", CultureInfo.InvariantCulture);

            var auditorias = from m in _context.TbAuditoria
                             where m.FeOperacion.Date >= auditoriaView.FeDesde
                             where m.FeOperacion.Date <= auditoriaView.FeHasta
                             /*
                             where m.FeOperacion.CompareTo(auditoriaView.FeDesde) >=0 &&
                                m.FeOperacion.CompareTo(auditoriaView.FeHasta) <= 0*/
                             select m;
            /*
            auditorias.Where(x => DateTime.Compare(x.FeOperacion.Date, auditoriaView.FeDesde) >= 0 &&
                                    DateTime.Compare(x.FeOperacion.Date, auditoriaView.FeHasta) <= 0);*/
            logger.Debug("Desde: " + auditoriaView.FeDesde);
            logger.Debug("Hasta: " + auditoriaView.FeHasta);

            AuditoriaView AuditoriaViewPage = new AuditoriaView();
            AuditoriaViewPage.FeDesde = auditoriaView.FeDesde;
            AuditoriaViewPage.FeHasta = auditoriaView.FeHasta;
            AuditoriaViewPage.Auditorias = auditorias.ToList();
            return View(AuditoriaViewPage);

            /*
            var dbCerebroContext = _context.TbAuditoria;
            return View(await dbCerebroContext.ToListAsync());*/
        }
    }
}

cerebro/Views/Auditoria/Index.cshtml
@model cerebro.Models.AuditoriaView
@{
    ViewData["Title"] = "Index";
}

<section class="content-header">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Reportes y Auditoria</a></li>
            <li class="breadcrumb-item active" aria-current="page">Auditoria</li>
        </ol>
    </nav>
</section>

<section class="content container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <form asp-controller="Auditoria" asp-action="Index">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-2">
                                <span>Fecha:</span>
                            </div>
                            <div class="col-2">
                                <span>Desde</span>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <input asp-for="StrFeDesde" type="text" class="form-control float-left" id="FeDesde">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="far fa-calendar-alt"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-2">
                                <span>Hasta</span>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <input asp-for="StrFeHasta" type="text" class="form-control float-left" id="FeHasta">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="far fa-calendar-alt"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer" align="center">
                        <input type="submit" value="Buscar" class="btn btn-primary" />
                        <input type="reset" value="Cancelar" class="btn btn-default" />
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-12">
            <div class="card">
                <!-- /.card-header -->
                <div class="card-header">
                    <h3 class="card-title">Listado de Operaciones</h3>

                </div>
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover" id="tbldata">
                        <thead>
                            <tr>
                                <th>Operación</th>
                                <th>Fecha Operación</th>
                                <th>Usuario</th>
                                <th>Contrato</th>
                                <th>Descripción Contrato</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Auditorias)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TipoOperacion)
                                </td>
                                <td>
                                    @Convert.ToDateTime(item.FeOperacion).ToString("dd/MM/yyyy")
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UsuarioOperacion)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NuContrato)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DeContrato)
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {

            $('#FeDesde').daterangepicker({
                singleDatePicker: true,
                locale: {
                    format: 'DD/MM/YYYY'
                }
            });

            $('#FeHasta').daterangepicker({
                singleDatePicker: true,
                locale: {
                    format: 'DD/MM/YYYY'
                }
            });

            $('#tbldata').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "language": {
                    "info": "Mostrando del _START_ al _END_ de _TOTAL_ registros"
                }
            });            
        });
    </script>
</section>                  